### PR TITLE
Adds `fit` method accepting precomputed transposed dataset

### PR DESCRIPTION
**Pull request by feynmanliang**
Required by jkbradley/spark-perf/pull/1

@fabuzaid21 @jkbradley

### CODE REVIEW

**Comment by jkbradley** [comment]
@feynmanliang Thanks for the PR.  It looks good, but I had one thought: It'd be nice to be able to prepare more of the data in the future, such as a collected set of labels, or even the initialized PartitionInfo.  Could you please modify this so that it wraps the transposed data in a new class with ```private[ml]``` constructors and accessors?

**Comment by feynmanliang** [comment]
How would the integration with Spark perf work? Spark perf needs to
instantiate this transposed dataset before timing so it needs access to a
method in spark.ml which can call the private constructor. Should we make
createColumnStore (not 100% on the exact method name) in Tree Utility
public?

**Comment by feynmanliang** [comment]
@jkbradley fixed merge conflicts

**Comment by jkbradley** [comment]
Yes, that's what I had in mind: We can make some public (DeveloperApi) method createColumnStore for spark-perf to use.

**Comment by jkbradley** [comment]
LGTM.  Thanks for fixing the conflicts.  I'm testing it locally, after which I'll merge it.

@fabuzaid21  I'll merge this and [https://github.com/jkbradley/spark-perf/pull/1]  (once I test both).  They should be helpful for your timing tests.

**Comment by fabuzaid21** [comment]
Sounds good!

**Comment by jkbradley** [comment]
Tests passed, so merging

**Pull request merged**
